use ticketbooking;

INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 1, 'Mỹ Tâm', 'Music', 'Mỹ Tâm sẽ phác họa chân thực toàn bộ những diễn biến tâm lý và cảm xúc vui buồn, khó khăn cùng những thăng hoa trong suốt quá trình thực hiện Liveshow Tri Âm lịch sử bằng những thước phim quý giá được quay lại trong 2 năm.','', 110, 1, 'Tiếng Việt', 'https://tse2.mm.bing.net/th?id=OIP.56H07oeZ08235npI6TGI8QHaEK&pid=Api&P=0', 'Tri Âm The Movie: Người Giữ Thời Gian', '2023-04-08', 'https://tse1.mm.bing.net/th?id=OIP.xSdUaneqYxt-EWlmWNlaQQHaJQ&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    VALUES (10, 'Anthony Russo,  Joe Russo', 'Phim lẻ, Hành động, Khoa học viễn tưởng, Phiêu lưu', 'Sau chuyến hành trình độc nhất vô nhị không ngừng mở rộng và phát triển vụ trũ điện ảnh Marvel, bộ phim Avengers: Cuộc Chiến Vô Cực sẽ mang đến màn ảnh trận chiến cuối cùng khốc liệt nhất mọi thời đại. Biệt đội Avengers và các đồng minh siêu anh hùng của họ phải chấp nhận hy sinh tất cả để có thể chống lại kẻ thù hùng mạnh Thanos trước tham vọng hủy diệt toàn bộ vũ trụ của hắn.', 'Thủ Đức', 150, 1, 'Tiếng Anh', 'https://i.imgur.com/B2GFZ15.jpg','Avengers: Cuộc Chiến Vô Cực','2023-04-25', 'https://tse4.mm.bing.net/th?id=OIP.qKWbILTyv3kEiHGnK-4V_gHaEK&pid=Api&P=0'  );
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 3, 'Lý Hải', 'Hài hước, Hành động', 'Lật Mặt: Ba Chàng Khuyết là câu chuyện đặc biệt về 3 chàng trai. Đức với tính cách ba phải, hoạt ngôn đến “lắm điều”; Lộc, một người có tính tình cố chấp và nóng nảy; và Tâm, một người hiền lành, cởi mở và luôn sẵn lòng giúp đỡ mọi người.','toàn quốc', 100, 0, 'Tiếng Việt', 'https://tse2.mm.bing.net/th?id=OIP.NAwGVhnp9uK0McpqnaXnYgHaD4&pid=Api&P=0', 'Lật Mặt: 3 Chàng Khuyết', '2023-05-10', 'https://tse4.mm.bing.net/th?id=OIP.Qcjwxir-UzLnrn0i23SF5wAAAA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 4, 'Gotoge Koyoharu', 'Phim hoạt hình, Phiêu lưu, Kỳ ảo đen tối, kiếm thuật', 'Gia đình bị thảm sát còn em gái trúng lời nguyền sau cuộc tấn công của ác quỷ, Tanjiro bước vào hành trình đầy hiểm nguy để đưa cô bé trở lại làm người và báo thù','', 150, 1, 'Lồng tiếng Việt', 'https://tse2.mm.bing.net/th?id=OIP.gB-Mw6g3PqVqSdkvylV4hgHaEK&pid=Api&P=0', 'Thanh gươm diệt quỷ 3: Làng thợ rèn', '2023-04-22', 'https://tse2.mm.bing.net/th?id=OIP.2PjHOTLbfOYHhwly9NtwAAHaHa&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 5, 'Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black, Keegan-Michael Key', 'Movie - Comedy, Adventure, Animation, Family, Fantasy', 'Cuộc phiêu lưu đến Vương quốc Nấm của anh chàng thợ sửa ống nước Mario và quá trình anh vươn lên trở thành một huyền thoại.','', 93, 1, 'Lồng tiếng Việt', 'https://tse3.mm.bing.net/th?id=OIP.tg1iamam5--pvDQtORDqawHaE7&pid=Api&P=0', 'Anh Em Super Mario', '2023-04-07', 'https://tse3.mm.bing.net/th?id=OIP.KXA44ShxHtBG8dCcQQqwyAHaKl&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 6, 'Russell Crowe, Daniel Zovatto, Alex Essoe, Franco Nero, Laurel Marsden', 'The Pope Exorcist - Mystery, Horror', 'Lấy cảm hứng từ những hồ sơ có thật của Cha Gabriele Amorth, Trưởng Trừ Tà của Vatican, bộ phim The Popes Exorcist theo chân Amorth trong cuộc điều tra về vụ quỷ ám kinh hoàng của một cậu bé và dần khám phá ra những bí mật hàng thế kỷ mà Vatican đã cố gắng giấu kín.','', 112, 1, 'Tiếng Anh', 'https://tse4.mm.bing.net/th?id=OIP.qrA3pC8z6PAUhgQSCJYh0AHaD4&pid=Api&P=0', 'Khắc Tinh Của Quỷ', '2023-04-14', 'https://tse2.explicit.bing.net/th?id=OIP.UL-1xQVihnGdIGiU6mnHAAGTJk&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 7, 'Shūgo Nakamura, Jun Kasama, Shinichiro Kamio, Subaru Kimura, Kenta Miyake', 'The First Slam Dunk - Comedy, Drama, Animation', ' The First Slam Dunk khắc họa việc bóng rổ có ảnh hưởng to lớn như thế nào đến sự trưởng thành của mỗi thành viên Shohoku.','', 124, 1, 'Lồng tiếng Việt', 'https://tse2.mm.bing.net/th?id=OIP.pCzp0_WJd5YCjQasq9DiAwHaFJ&pid=Api&P=0', 'Cú Úp Rổ Đầu Tiên', '2023-04-14', 'https://tse3.mm.bing.net/th?id=OIP.m1jinzwQoa5rPFLfV6Js-AHaLH&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 8, 'Jake Gyllenhaal, Dar Salim, Antony Starr, Alexander Ludwig, Emily Beecham', 'The Covenant - Action, Drama, War', 'Trong nhiệm vụ cuối cùng ở Afghanistan, Trung sĩ John Kinley cùng đội với phiên dịch viên bản địa Ahmed. Khi đơn vị của họ bị phục kích, Kinley và Ahmed là 2 người sống sót duy nhất. ','', 123, 1, 'Tiếng Anh', 'https://tse4.mm.bing.net/th?id=OIP.6y7uKYZDh6X7HI4qoeDbZwHaE6&pid=Api&P=0', 'Khế Ước', '2023-04-21', 'https://tse3.mm.bing.net/th?id=OIP.5LdPYDvlTjPhmyNj9aiVYAHaK-&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 9, 'Mạc Văn Khoa, Anh Tú, Ngọc Phước, Nhất Trung, NSƯT Mỹ Duyên', 'Comedy, Drama', 'Thuộc phong cách hành động – hài hước với các “cú lừa” thông minh và lầy lội đến từ bộ đôi Tú (Anh Tú) và Khoa (Mạc Văn Khoa), Siêu Lừa Gặp Siêu Lầy của đạo diễn Võ Thanh Hòa theo chân của Khoa – tên lừa đảo tầm cỡ “quốc nội” đến đảo ngọc Phú Quốc với mong muốn đổi đời..','', 135, 1, 'Tiếng Việt', 'https://tse3.mm.bing.net/th?id=OIP.bl_0KwydFOfXDu1swcmEBAHaEK&pid=Api&P=0', 'Siêu Lừa Gặp Siêu Lầy', '2023-03-13', 'https://tse3.mm.bing.net/th?id=OIP.1X8OCsoBlK1Cq38RVTRsfgHaKX&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 2, 'Matt Damon, Ben Affleck, Jason Bateman, Chris Messina, Matthew Maher', 'Air - Drama', 'Từ đạo diễn đã từng đoạt giải thưởng Ben Affleck, AIR hé lộ mối quan hệ đột phá giữa huyền thoại Michael Jordan khi mới bắt đầu sự nghiệp và bộ phận bóng rổ còn non trẻ của Nike, đã làm thay đổi thế giới thể thao và văn hóa đương đại với thương hiệu Air Jordan. Câu chuyện cảm động này kể về sự đánh cược khi đặt lên bàn cân tình hình kinh doanh của cả công ty, tầm nhìn vĩ đại của một người mẹ biết giá trị và tài năng của con trai mình, và một siêu sao bóng rổ đã trở thành huyền thoại.','', 112, 1, 'Tiếng Anh', 'https://tse2.mm.bing.net/th?id=OIP.s90UNWfBwSPSfC1mE-UOnAHaFM&pid=Api&P=0', 'Air: Theo Đuổi Một Huyền Thoại', '2023-04-14', 'https://tse1.mm.bing.net/th?id=OIP.ixycjp1ceAPmsaS02xzeRQHaK-&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 11, '', 'Cats in the Museum - Comedy, Animation', 'Mèo Siêu Quậy Ở Viện Bảo Tàng','', 80, 0, 'Lồng tiếng Việt', 'https://tse4.mm.bing.net/th?id=OIP.gCaADhRPgtzD11B-d-qzqgDzFo&pid=Api&P=0', 'Mèo Siêu Quậy Ở Viện Bảo Tàng', '2023-04-28', 'https://tse4.mm.bing.net/th?id=OIP.gCaADhRPgtzD11B-d-qzqgDzFo&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 12, 'Kim Bo-ra, Kim Jae-hyun, Shin So-yul', 'The Ghost Station - Horror', 'Lời đồn ma ám về nhà ga Oksu ngày càng nhiều khi những vụ án kinh hoàng liên tục xảy ra. Một đường ray cũ kỹ, một chiếc giếng bỏ hoang, những con số gây ám ảnh hay những vết thương kỳ dị trên thi thể người xấu số... Tất cả dẫn đến một bí mật đau lòng bị chôn vùi nhiều năm trước.','', 80, 0, 'Tiếng Hàn', 'https://tse4.mm.bing.net/th?id=OIP.GXsAm36eWoluuU5ujYT3ygHaL1&pid=Api&P=0', 'Trạm Tàu Ma', '2023-04-28', 'https://tse4.mm.bing.net/th?id=OIP.GXsAm36eWoluuU5ujYT3ygHaL1&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 13, 'Chris Pratt, Zoe Saldana, Dave Bautista, Karen Gillan, Pom Klementieff', 'Guardians of the Galaxy Volume 3 - Comedy, Adventure, Science Fiction', 'Cho dù vũ trụ này có bao la đến đâu, các Vệ Binh của chúng ta cũng không thể trốn chạy mãi mãi.','', 149, 0, 'Tiếng Anh', 'https://tse1.mm.bing.net/th?id=OIP.KM1n42-PlP9jkIGxSgnPzgHaEc&pid=Api&P=0', 'Vệ Binh Dải Ngân Hà 3', '2023-05-03', 'https://tse4.mm.bing.net/th?id=OIP.MYVuPGbICjrqMbx_KAkW7QHaLU&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 14, 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson, Ludacris, Jason Momoa', 'Fast X - Action, Thriller, Crime', 'Fast & Furious 10','', 130, 0, 'Tiếng Anh', 'https://tse3.mm.bing.net/th?id=OIP.xdHFGVcYKSMzHLqj4xEAWgHaEK&pid=Api&P=0', 'Fast & Furious 10', '2023-05-17', 'https://tse1.mm.bing.net/th?id=OIP.4sieUZqdRS5P9NEZSznflQHaJ0&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 15, 'Joshua Dela Cruz, Steve Burns, Donovan Patton, Traci Paige Johnson, Nick Balaban', 'Blue is Big City Adventure - Adventure, Animation, Family, Musical, Music', 'Blue is Big City Adventure','', 74, 0, 'Tiếng Anh', 'https://tse1.mm.bing.net/th?id=OIP.cIHnnMqsYLzUASQqU14mxQHaD4&pid=Api&P=0', 'Blue is Big City Adventure', '2023-05-11', 'https://tse3.mm.bing.net/th?id=OIP.bxAEUOwuj-kJC3tWO8yoPwHaK-&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 16, 'Jorma Tommila, Aksel Hennie, Jack Doolan, Onni Tommila, Mimosa Willamo', 'Sisu - Action, War', 'Khi một cựu quân nhân phát hiện ra vàng ở vùng hoang dã Lapland cố gắng mang chiến lợi phẩm vào thành phố, những người lính Đức Quốc xã do một sĩ quan SS tàn bạo chỉ huy đã chiến đấu với anh ta.','', 122, 0, 'Lồng tiếng Việt', 'https://tse4.mm.bing.net/th?id=OIP.jWqZa8eBRHKkVnLaC7mPkQHaEK&pid=Api&P=0', 'Thám Tử Lừng Danh Conan: Tàu Ngầm Sắt Màu Đen', '2023-07-21', 'https://tse4.mm.bing.net/th?id=OIP.jWqZa8eBRHKkVnLaC7mPkQHaEK&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 17, 'Halle Bailey, Jonah Hauer-King, Daveed Diggs, Awkwafina, Jacob Tremblay', 'The Little Mermaid - Romance, Adventure, Family, Fantasy', 'A young mermaid makes a deal with a sea witch, to trade her beautiful voice for human legs so she can discover the world above water and impress a prince.','', 135, 0, 'Tiêng Anh', 'https://tse3.mm.bing.net/th?id=OIP.y5sJWIz6ZCIbhDOzFGk06wHaEK&pid=Api&P=0', 'Nàng Tiên Cá', '2023-05-26', 'https://tse4.mm.bing.net/th?id=OIP.D6VJFyQeHYk3grEqTaEY6wAAAA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 18, 'Ezra Miller, Kiersey Clemons, Billy Crudup, Johnny Depp', 'The Flash - Action, Adventure, Fantasy, Science Fiction', 'Trong nguyên tác truyện tranh, anh chàng Barry Allen sẽ quay ngược thời gian để cứu người mẹ khỏi cái chết. Chuyến đi này của anh đã làm thay đổi nhiều sự kiện trong quá khứ và từ đó kéo theo một loạt rắc rối.','', 120, 0, 'Tiếng Anh', 'https://tse3.mm.bing.net/th?id=OIP.dGsx_9QLfJvX9hoiiLS9sAHaEo&pid=Api&P=0', 'Flash', '2023-06-16', 'https://tse1.mm.bing.net/th?id=OIP.8P6dHvcSDgebhViEkXf97QHaJQ&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 19, 'Brie Larson, Iman Vellani, Teyonah Parris, Zawe Ashton', 'The Marvels - Action, Adventure, Fantasy, Science Fiction', 'Biệt Đội Marvel','', 121, 0, 'Tieenga Anh', 'https://tse4.mm.bing.net/th?id=OIP.R4aoZoHvuOwmB8LNY-5UXAHaEK&pid=Api&P=0', 'Biệt Đội Marvel', '2023-11-10', 'https://tse2.mm.bing.net/th?id=OIP.VZjcMQbCjkhUpyE_H4W_MAHaHA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 20, 'Anthony Ramos, Dominique Fishback, Tobe Nwigwe, Peter Cullen, Ron Perlman', 'Transformers: Rise of the Beasts - Action, Adventure, Science Fiction', 'Transformers: Quái Thú Trỗi Dậy','', 100, 0, 'Tiếng Anh', 'https://tse3.mm.bing.net/th?id=OIP.XY-pbjjo9VsDgmYmImoeigHaEK&pid=Api&P=0', 'Transformers: Quái Thú Trỗi Dậy', '2023-06-07', 'https://tse2.mm.bing.net/th?id=OIP.2RDw4GTJp4CEkVZjCc1rcAHaLH&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 21, 'Shameik Moore', 'Spider-Man: Across the Spider-Verse - Comedy, Action, Adventure, Animation, Science Fiction', 'Vô số Spider-Man từ khắp các vũ trụ đang đối đầu nhau?!','', 121, 0, 'Tieenga Anh', 'https://tse3.mm.bing.net/th?id=OIP.Mt6NlBanp2Vty-Lz_yvPLwHaDF&pid=Api&P=0', 'Người Nhện: Du Hành Vũ Trụ Nhện', '2023-06-01', 'https://tse3.mm.bing.net/th?id=OIP.Fk9NymqjT8amweM57lEN6wAAAA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 22, 'Ty Simpkins, Patrick Wilson, Hiam Abbass, Sinclair Daniel, Andrew Astor', 'Insidious: The Red Door - Thriller, Horror', 'Quỷ Quyệt Cửa Đỏ Vô Định','', 100, 0, 'Tiếng Anh', 'https://tse4.mm.bing.net/th?id=OIP.rvqNc9hhGfjEKg3Mh8RhDQHaEK&pid=Api&P=0', 'Quỷ Quyệt Cửa Đỏ Vô Định', '2023-07-07', 'https://tse3.mm.bing.net/th?id=OIP.nvvHdlW7lUikUO5mO6AwUAAAAA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 23, 'Sam Worthington, Zoe Saldana, Stephen Lang, Sigourney Weaver, Oona Chaplin', 'Avatar 3 - Action, Drama, Adventure, Fantasy, Science Fiction', 'Plot unknown.','', 123, 0, 'Tiếng Anh', 'https://tse4.mm.bing.net/th?id=OIP.sLR_XespC94D6uNGntpHoAHaEA&pid=Api&P=0', 'Avatar 3', '2023-12-22', 'https://tse3.mm.bing.net/th?id=OIP.l-En78CeRmg02kWv6d_V6AHaLH&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 24, 'Thitiya Jirapornsilp, Anthony Buisseret, Supakson Chaimongkol, Natee Ngamneawprom, Karuna Looktumthong', 'You & Me & Me - Romance, Drama', ' Tình chị em tưởng chừng không thể rạn nứt cho đến khi chàng trai Mark chen vào giữa họ.','', 121, 1, 'Tiếng Thái', 'https://tse2.mm.bing.net/th?id=OIP.VBUk3gPejDd_szE3AT1ocgHaEK&pid=Api&P=0', 'Tình Chị Duyên Em', '2023-04-07', 'https://tse4.mm.bing.net/th?id=OIP.vJ4SbkXhnTTA2QfA4wzoJgHaJR&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 25, 'Henry Golding, Daniela Melchior, Jimmy Jean-Louis, Noomi Rapace, Sam Neill', 'Assassin Club - Action, Thriller', '7 tên sát thủ đến từ khắp nơi trên thế giới vô tình được thiết lập trong một trò chơi sống còn.','', 110, 1, 'Tiếng Anh', 'https://tse3.mm.bing.net/th?id=OIP.o5HT_2QPQCOJ2tXGupY-xAHaEV&pid=Api&P=0', 'Câu Lạc Bộ Sát Thủ', '2023-04-07', 'https://tse2.mm.bing.net/th?id=OIP.lpE5zSTmHR-huEbYtaf5NQAAAA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 26, 'Greg Hsu, Austin Lin, Gingle Wang, Tsai Chen-Nan, Ma Nien-Hsien', 'Marry My Dead Body - Comedy, Action, Mystery, Thriller', 'Một ngày nọ, trong quá trình truy bắt tội phạm cùng người đồng nghiệp xinh đẹp Zi-Qing, Ming-Han vô tình nhặt được một phong bao màu đỏ, và một nhóm người bất ngờ nhảy ra gọi anh là con rể','', 130, 0, 'Tiếng Trung', 'https://tse1.mm.bing.net/th?id=OIP.4BWwQ81zuIySrCWQxkZ-kQHaKe&pid=Api&P=0', 'Chuyện Tôi Và Ma Quỷ Thành Người Một Nhà', '2023-04-07', 'https://tse1.mm.bing.net/th?id=OIP.4BWwQ81zuIySrCWQxkZ-kQHaKe&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 27, 'Marie-Madeleine Burguet, Catherine Lafond, Célia Rosich, Enrico Di Giovanni, Thomas Sagols', 'The Prince Voyage - Animation', 'Hoàng tử khỉ già mắc cạn ở một bờ biển không xác định. Bị thương và mất tích, cậu được cậu bé Tom 12 tuổi tìm thấy và được cha mẹ cậu, những nhà khoa học, những người đã bị trục xuất khỏi cộng đồng của họ, nhận nuôi','', 75, 1, 'Lồng tiếng Việt', 'https://tse3.mm.bing.net/th?id=OIP.BiMnhjZ8VS4nY2g6pXetTwHaEK&pid=Api&P=0', 'Cuộc Phiêu Lưu Của Hoàng Tử', '2023-04-08', 'https://tse3.mm.bing.net/th?id=OIP.H8QeqnDfyau5vShYx-IViwHaJ4&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 28, 'Michaela Longden, Rebecca Phillipson, Tom Millen, Victor Mellors, Simon Davies', 'The Ghost Within - Horror', ' Bí ẩn về cái chết của em gái Evie 20 năm trước còn bỏ ngỏ, vào lúc 09:09 hằng đêm, hàng loạt cuộc chạm trán kinh hoàng xảy ra.','', 103, 1, 'Tiếng Anh', 'https://tse4.mm.bing.net/th?id=OIP.s8-JLC9W3uXIZSSLRqFyCgHaEq&pid=Api&P=0', 'Mặt Nạ Quỷ', '2023-04-14', 'https://tse1.mm.bing.net/th?id=OIP.eY6MzGP8fGjryFrOrXFlRgHaHa&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 29, 'Chanya McClory, Kritsanapoom Pibulsonggram, Bhumibhat Thavornsiri, Krissada Sukosol Clapp, Nopachai Chaiyanam', 'Inhuman Kiss: The Last Breath - Romance, Drama, Fantasy, Horror', 'Khi Ma Lai rung động với chàng trai bị nguyền rủa, mối tình lãng mạn nhưng cũng vô cùng rùng rợn liệu có lối thoát? Cloud (Jayler Krissanapoom) sinh ra với chứng rối loạn di truyền dẫn tới bệnh bạch tạng.','', 122, 1, 'Tiếng Thái', 'https://tse1.mm.bing.net/th?id=OIP.4eJ-CO4b2A6yR5uCCqnlOwHaEK&pid=Api&P=0', 'Ma Lai Rút Ruột', '2023-04-28', 'https://tse4.explicit.bing.net/th?id=OIP.j_u_bxW5ntflAyD08YhNzQAAAA&pid=Api&P=0');
INSERT INTO movie (id,actors, categories, description, director, duration, is_showing, language, large_imageurl, name, release_date, small_imageurl)
    values( 30, 'Vincent Lacoste, Benoît Poelvoorde, Mathieu Capella, Anaïs Demoustier, Noémie Lvovsky', 'Father And Sons - Comedy, Drama', 'Joseph và hai con trai của ông, Joachim và Ivan, tạo thành một gia đình gắn bó nhưng không nhận ra rằng mỗi người đang mất kiểm soát cuộc sống của mình.','', 90, 1, 'Tiếng Anh', 'https://tse4.mm.bing.net/th?id=OIP.Ar-aL5lxQJKm6TH5DT33igHaEK&pid=Api&P=0', 'Con Trai', '2023-04-15', 'https://tse3.mm.bing.net/th?id=OIP.Um9YWYiJFfkw0Jj1aRqnIwHaKl&pid=Api&P=0');
